# Generated by Django 2.1.9 on 2020-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategoryData',
            fields=[
                ('Category_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'StoreCategoryData',
            },
        ),
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('Store_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Store_Name', models.CharField(max_length=100)),
                ('Store_Owner', models.CharField(max_length=100)),
                ('Store_Category', models.CharField(max_length=100)),
                ('Store_Email', models.CharField(max_length=100)),
                ('Store_Phone', models.CharField(max_length=100)),
                ('Store_Password', models.CharField(max_length=100)),
                ('Store_Address', models.CharField(default='NA', max_length=100)),
                ('Store_City', models.CharField(default='NA', max_length=100)),
                ('Store_State', models.CharField(default='NA', max_length=100)),
                ('Status', models.CharField(default='Active', max_length=100)),
            ],
            options={
                'db_table': 'StoreData',
            },
        ),
    ]
