# Generated by Django 2.1.9 on 2020-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200528_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLogoData',
            fields=[
                ('Store_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Store_Logo', models.FileField(upload_to='storelogo/')),
            ],
            options={
                'db_table': 'StoreLogoData',
            },
        ),
    ]
