# Generated by Django 2.1.9 on 2020-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200528_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductCategoryData',
            fields=[
                ('Store_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Product_Category_ID', models.CharField(max_length=100)),
                ('Product_Category_Name', models.CharField(max_length=500)),
                ('Product_Category_Image', models.FileField(upload_to='productcategory/')),
            ],
            options={
                'db_table': 'StoreProductCategoryData',
            },
        ),
    ]
