# Generated by Django 2.1.9 on 2020-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_storedata_verify_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='Store_Category',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
