# Generated by Django 2.1.9 on 2020-05-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200531_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBannerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_ID', models.CharField(max_length=100)),
                ('Store_Banner', models.FileField(upload_to='storebanner/')),
            ],
            options={
                'db_table': 'StoreBannerData',
            },
        ),
        migrations.AddField(
            model_name='storeproductdata',
            name='Product_Expiry',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AddField(
            model_name='storeproductdata',
            name='Product_Stock',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
