# Generated by Django 2.1.9 on 2020-06-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200531_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('User_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('User_Fname', models.CharField(max_length=100)),
                ('User_Lname', models.CharField(max_length=100)),
                ('User_Email', models.CharField(max_length=150)),
                ('User_Mobile', models.CharField(max_length=100)),
                ('User_Password', models.CharField(max_length=50)),
                ('Status', models.CharField(default='Active', max_length=50)),
                ('Verify_Status', models.CharField(default='Unverified', max_length=50)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
        migrations.AlterField(
            model_name='storeproductimagedata',
            name='Product_Image',
            field=models.FileField(upload_to='product/'),
        ),
    ]
