# Generated by Django 2.1.9 on 2020-06-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200602_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddressData',
            fields=[
                ('Address_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('User_ID', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('HouseStreet', models.CharField(max_length=100)),
                ('LandmarkColony', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserAddressData',
            },
        ),
    ]
