# Generated by Django 2.1.9 on 2020-06-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_useraddressdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('Cart_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Store_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'CartData',
            },
        ),
        migrations.CreateModel(
            name='CartProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Add_Date', models.CharField(default='04/06/2020', max_length=50)),
                ('Cart_ID', models.CharField(max_length=100)),
                ('Store_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
                ('Product_ID', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'CartProductData',
            },
        ),
    ]
