# Generated by Django 2.1.9 on 2020-06-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cartdata_cartproductdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductdata',
            name='Product_Quantity',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
