# Generated by Django 2.1.9 on 2020-06-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cartproductdata_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='Cart_Price',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cartproductdata',
            name='Product_Total',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
