# Generated by Django 2.1.9 on 2020-06-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_orderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='Status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartproductdata',
            name='Product_Add_Date',
            field=models.CharField(default='05/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='Order_Date',
            field=models.CharField(default='05/06/2020', max_length=50),
        ),
    ]
