# Generated by Django 2.1.9 on 2020-06-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200605_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(default='None', max_length=100)),
                ('MERCHANT_KEY', models.CharField(default='None', max_length=100)),
                ('CURRENCY', models.CharField(default='None', max_length=100)),
                ('GATEWAYNAME', models.CharField(default='None', max_length=100)),
                ('RESPMSG', models.CharField(default='None', max_length=1000)),
                ('BANKNAME', models.CharField(default='None', max_length=100)),
                ('PAYMENTMODE', models.CharField(default='None', max_length=100)),
                ('MID', models.CharField(default='None', max_length=100)),
                ('RESPCODE', models.CharField(default='None', max_length=100)),
                ('TXNID', models.CharField(default='None', max_length=100)),
                ('TXNAMOUNT', models.CharField(default='None', max_length=100)),
                ('STATUS', models.CharField(default='None', max_length=100)),
                ('BANKTXNID', models.CharField(default='None', max_length=100)),
                ('TXNDATE', models.CharField(default='None', max_length=100)),
                ('CHECKSUMHASH', models.CharField(default='None', max_length=100)),
            ],
            options={
                'db_table': 'OrderPaymentData',
            },
        ),
    ]
