# Generated by Django 2.1.9 on 2020-06-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_orderpaymentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMerchantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_ID', models.CharField(max_length=100)),
                ('MID', models.CharField(max_length=500)),
                ('MERCHANT_KEY', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'StoreMerchantData',
            },
        ),
    ]
