# Generated by Django 2.1.9 on 2020-06-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200606_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='Order_Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
