# Generated by Django 2.1.9 on 2020-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_orderdata_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductRatingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_ID', models.CharField(max_length=100)),
                ('Product_ID', models.CharField(max_length=100)),
                ('Rating', models.CharField(default='0', max_length=100)),
            ],
            options={
                'db_table': 'StoreProductRatingData',
            },
        ),
    ]
