# Generated by Django 2.1.9 on 2020-06-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_storeproductratingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductimagedata',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartproductdata',
            name='Product_Add_Date',
            field=models.CharField(default='08/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='Order_Date',
            field=models.CharField(default='08/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='storeproductimagedata',
            name='Product_ID',
            field=models.CharField(max_length=100),
        ),
    ]
