# Generated by Django 2.1.9 on 2020-06-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200608_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('Agent_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'AgentData',
            },
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('Feedback_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Feedback', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'FeedbackData',
            },
        ),
        migrations.AlterField(
            model_name='cartproductdata',
            name='Product_Add_Date',
            field=models.CharField(default='11/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='Order_Date',
            field=models.CharField(default='11/06/2020', max_length=50),
        ),
    ]
