# Generated by Django 2.1.9 on 2020-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200611_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='Feedback_Date',
            field=models.CharField(default='12/06/2020', max_length=15),
        ),
        migrations.AlterField(
            model_name='cartproductdata',
            name='Product_Add_Date',
            field=models.CharField(default='12/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='Order_Date',
            field=models.CharField(default='12/06/2020', max_length=50),
        ),
    ]
