# Generated by Django 2.1.9 on 2020-06-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200612_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductdata',
            name='Product_Add_Date',
            field=models.CharField(default='23/06/2020', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='Feedback_Date',
            field=models.CharField(default='23/06/2020', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='Order_Date',
            field=models.CharField(default='23/06/2020', max_length=50),
        ),
    ]
